### ISSUE TITLE
Support for parenthesized type declarations

### ISSUE THREAD

**Issue by rlankfo** [jfeliu007/goplantuml#102]
I had several parenthesized interface type declarations and noticed they weren't showing up in the puml output. 

Examples)
Works:
```
type Foo interface {
  Foo()
}
type Bar interface {
  Bar()
}
```

Not working:
```
type (
  Foo interface {
    Foo()
  }
  Bar interface {
    Bar()
  }
)
```

**Comment by jfeliu007** [comment]
I'll take a look at this. Thanks for reporting it.

**Comment by rlankfo** [comment]
Thanks. If you could provide some direction I wouldn't mind taking a crack at a PR.

**Comment by jfeliu007** [comment]
Actually I would have to see how the AST represents this specific problem. Let me make a couple of tests to see if I can suggest a COA. Thanks for this and sorry for the delays in my responses. I think I have to hook some notifications in this repo. I only see these updates if I come to github.

**Comment by jfeliu007** [comment]
I just took a look at this. In the fileparser/class_parser.go near to line 320 the code assumes the dec.Specs array will only contain 1 element. I have never seen the declarations as you posted in this issue and of course never ran into this case. If you wrap the code from 321 to 370 around a for loop range on each Spec you will solve this issue. :)
