### ISSUE TITLE
Create a Github Action of goplantuml

### ISSUE THREAD

**Issue by jermon** [jfeliu007/goplantuml#112]
It would be very good if we can create a Github Action of goplantuml to create a picture on the build.

**Comment by jfeliu007** [comment]
Hi @jermon , can you add more details on this issue? goplantuml does not creates pictures of any kind.

**Comment by jermon** [comment]
No, but it can create a input file for PlantUML and PlantUML can create pictures.

**Comment by tbal999** [comment]
@jermon -> https://github.com/tbal999/pumlaction

the action above makes use of bykof/go-plantuml repo - but you may be able to adjust it to work for your purposes.

**Comment by jermon** [comment]
Thank you @tbal999. That s exactly what I was aiming for.

**Comment by tbal999** [comment]
I guess this can be closed then?
Feel free to fork the repo, let me know how it goes!

**Comment by jermon** [comment]
yes it can. Thank you.
