### ISSUE TITLE
Install issue: no module found

### ISSUE THREAD

**Issue by BigBoulard** [jfeliu007/goplantuml#113]
Hi,

I've followed the install procedure but something is not working.
```
$ pwd
/Users/BigBoulard/dev/go/src/github.com/jfeliu007/goplantuml
$ BigBoulard@macOS:goplantuml $ go install ./...
go: cannot find main module, but found .git/config in /Users/BigBoulard/dev/go/src/github.com/jfeliu007/goplantuml
        to create a module there, run:
        go mod init
```

Thanks for your help.

Kind regards.

**Comment by jfeliu007** [comment]
Hi @BigBoulard , I think there this might work. I tried it with the latest version of golang. I might need to update the readme file for this. Try executing this command instead. 
`go install github.com/jfeliu007/goplantuml/cmd/goplantuml@latest`
