### ISSUE TITLE
How to use the generated .puml file?

### ISSUE THREAD

**Issue by TENX-S** [jfeliu007/goplantuml#142]
Can I turn it into png? https://www.dumels.com/ only support URL. Can I use it for private repo?

**Comment by jfeliu007** [comment]
Hi @TENX-S , dumels.com does not support private repos for now, unfortunately. I suggest you visit [plantuml](https://www.plantuml.com/plantuml/uml/SyfFKj2rKt3CoKnELR1Io4ZDoSa70000) if you want to turn the puml file into a png for now.
