### ISSUE TITLE
Newline at end of output

### ISSUE THREAD

**Issue by dpedu** [jfeliu007/goplantuml#17]
Currently, when ran in a shell, the output from the program looks like this:

```
dave@davespc$ goplantuml foobar.go
@startuml
...
...
...
@endumldave@davespc$ 
```

Note that the `@enduml` tag is printed without a trailing newline, causing it to be smashed into the shell prompt. 

It would be a slightly nicer experience if the output contained a trailing newline.

**Comment by jfeliu007** [comment]
I thought of it too; however, since there is more use for this output as a file, I decided not to include the new line at the end. 

I think most people would use this as following
```
goplantuml ./ > Diagram.puml
```
in which case the new line at the end is not necessary. Do you still see value on it anyways?

**Comment by dpedu** [comment]
You're right, the output of this program is just about always going to be piped to a file. Though, you'd see the same thing if you `cat` the file to inspect it for whatever reason, maybe looking at it on the command line for a quick overview of some code.

I don't have a particular need for this, it's kind of a pet peeve 😀.

**Comment by jfeliu007** [comment]
This is a quick fix. I'll pop it into the next revision. Thanks for your input. 👍
