### ISSUE TITLE
Enhancement: Proposal to pass multiple subfolder in a folder

### ISSUE THREAD

**Issue by sum2000** [jfeliu007/goplantuml#29]
Proposal to pass two folders in a subfolder to generate UML and relationship between two classes

**Comment by jfeliu007** [comment]
Could you provide an example of what you are suggesting?

**Comment by sum2000** [comment]
Assume a project folder like:
--FOO
---BAR
------BAR.GO
---BAZ
------BAZ.GO
---FOO.GO

It would be nice to have UML relationship diagram just between subfolders BAR and BAZ. In a large project, the UML diagram can get very complex with lots of boxes. This approach can help scope some classes.
