### ISSUE TITLE
Invalid edge for type

### ISSUE THREAD

**Issue by Justin-W** [jfeliu007/goplantuml#49]
I'm seeing the following invalid puml generated:

```plantuml
<font color=blue>func</font>() []*servicebridgeerrors.Error #.. utils.StructureValidatorMethod
```

I think the go code that is causing the above line is this:

```go
type StructureValidatorMethod func(interface{}) []*servicebridgeerrors.Error
```

**Comment by jfeliu007** [comment]
Thank @Justin-W .

**Comment by jfeliu007** [comment]
@Justin-W This might have been fixed by https://github.com/jfeliu007/goplantuml/pull/52

Is it possible for you to retest this to see if you still get invalid puml with the latest master branch?

**Comment by Justin-W** [comment]
> Is it possible for you to retest this to see if you still get invalid puml with the latest master branch?

#49 and #50 both seem to be fixed by latest master, insofar as the invalid edge lines are no longer included in the output. However, I wasn't able to see find (see #61) any new, valid edges corresponding to the invalid edges. It seems those invalid edges were removed rather than replaced. Was that the intent of the fix?

**Comment by jfeliu007** [comment]
The output should be included, just a bit different. I had to enclose some of the rendered connections in quotations because things like [] and * where breaking the diagram. 
I also had to modify the order of some of the components.
So something like
```<font color=blue>func</font>() []*servicebridgeerrors.Error #.. utils.StructureValidatorMethod```
would now render something like this
```"servicebridgeerrors.<font color=blue>func</font>() []*Error" #.. "utils.StructureValidatorMethod"```

The reason I had to move the package to the proper package in the diagram.

**Comment by Justin-W** [comment]
> should render something like this
> `"packagename.<font color=blue>func</font>() []*servicebridgeerrors.Error" #.. "utils.StructureValidatorMethod"`
> which is crucial for rendering the connection in the correct namespace

In that case, then it's not entirely/properly fixed. Both *before and after the fix*, I am seeing a puml class in the output, like this:

```go
namespace utils {
    class utils.StructureValidatorMethod << (T, #FF7700) >>  {
    }
}
```

However, **before** the fix, there was also the single edge/arrow line with the invalid syntax.

**After** the fix, there are **zero** edges/arrows in the output. So the output for that particular project no longer contains any invalid puml syntax. Therefore, if the edge that was broken before is supposed to have a corresponding (non-broken) edge after the fix, then that part of the fix is broken. (The same is also true for the previously-broken edge from #50. It is also now missing completely from the output.)

**Comment by Justin-W** [comment]
> I was not rendering the aliases. Which might be the reason why you saw zero edges in the output.

Confirmed. All of the alias edges weren't being rendered. After grabbing the latest today, the missing alias-related edges are back. However, there are now a **lot** of them. Instead of the 1 broken alias edge, the same project now has 46 identical (but valid and renderable!) edges like the following:

```plantuml
"utils.<font color=blue>func</font>() []*servicebridgeerrors.Error" #.. "utils.StructureValidatorMethod"
```

It also has over 1000 alias edges connected to the `int32` builtin. Only 22 of those 1012 are distinct/unique edges. E.g. This one also appears 46 times:

```plantuml
"__builtin__.int32" #.. "schedule.Day"
```

Since 22 * 46 = 1012, I'm assuming that each of the 22 distinct alias edges appears exactly 46 times in this project. Each of the ones I checked had exactly 46 occurrences.

Obviously, the 1125 redundant alias edges (1150 total - 25 unique) now make much of the rendered diagram unreadable.

**Comment by jfeliu007** [comment]
Interesting, this issue does not want to go away 🤣 . I'll take a deeper look.

**Comment by Justin-W** [comment]
FYI: It seems that each alias edge is now being rendered once per puml namespace in the output. E.g. 3 puml namespaces = 3 of each alias edge and 46 namespaces = 46 of each alias edge.

It looks like you are rendering all alias edges for the whole graph after each namespace is rendered, instead of just once at the end of rendering.

**Comment by jfeliu007** [comment]
I think I found the issue. I moved the alias rendering to a place for consistency without realizing the code needed to be in a global area. I'll have something soon for this. The tip you gave me about the 46 times was perfect.

**Comment by Justin-W** [comment]
Great. Thanks.

**Comment by Justin-W** [comment]
Verified fixed in master. 👍
