### ISSUE TITLE
{packageName} shows in edge output

### ISSUE THREAD

**Issue by Justin-W** [jfeliu007/goplantuml#50]
I'm seeing the following invalid puml generated:

```plantuml
[]{packageName}GroupConfig #.. mock.GroupConfigs
```

I think the go code that is causing the above line is this:

```go
var errNoDataFound = errors.New("No data found in the db")

type GroupConfigs []GroupConfig

type GroupConfig struct {
	Name string
	Jobs []string
}
```

I'm not sure why the above code would cause a problem, but there are no other code references to either `GroupConfig` or `GroupConfigs` so it seems like the only code that could possibly be related to the invalid puml output above.

FYI: This error seems possibly-related to #3, but since #3 has no details and is closed, I'm submitting this as a separate issue.

**Comment by Justin-W** [comment]
I'm also seeing a very similar error in the output from another project:

```plantuml
[]{packageName}HTTPRoute #.. server.HTTPRoutes
```

I think the go code that is causing the above line is this:

```go
// ...
}

type HTTPRoute struct {
// fields omitted ...
}

// HTTPRoutes is shorthand for a array of HTTPRoute
type HTTPRoutes []HTTPRoute

type Server struct {
// ...
```

**Comment by jfeliu007** [comment]
Thank you @Justin-W . I will take a look at this. This is definitely a bug. {{packageName}} is use to to have a placeholder to later substitute the package name by the real name since many go file prefer to name imports using aliases. I might be able to find this one soon.
