### ISSUE TITLE
Enhancement: Additional CLI options to control rendered output

### ISSUE THREAD

**Issue by Justin-W** [jfeliu007/goplantuml#51]
It would be nice if the `cmd` class supported some additional CLI flags to enable the CLI to be used to quickly generate common variations of the current output.

The benefit of having CLI flags such as the following would be that someone could easily render several different diagrams/graphs of the same golang package(s), since each variant diagram has different PROs and CONs as an exploratory (and/or explanatory) visualization.

Suggested rendering options:

* `-no-fields`: to hide/exclude Classes' "fields"
    This would be useful for simplifying/filtering the output. E.g. Reducing the size of the Class nodes (by including less intra-Class detail) simplifies the graph layout, and makes it easier to trace inter-Class relationships during an API review of the coupling between Classes.
* `-no-methods`: to hide/exclude Classes' "methods"
    Same rationale as previous, but for methods/functions instead of fields.
* `-no-fields -no-methods`: to hide/exclude all inner members of Classes
    Same rationale as previous, but for both methods/functions and fields.
    Hiding all intra-Class detail makes the graph **much** easier to use for identifying inter-Class coupling, etc.
* `-no-edges`: to hide/exclude all edges
    This would be useful to allow the output to be used as a template. E.g. So that custom edges can be added manually, but without having to manually remove all of the default edges.
    Also, since edges impact diagram layout (Class location), temporarily eliminating the edges can be useful for simplifying graph layout (e.g. to locate a particular Class/node).
* `-no-edgeless`: to hide/exclude all Classes **without** any edges/arrows
    This would be useful for simplifying/filtering the output. E.g. To easily exclude un-connected Classes during an API review of the coupling between Classes.
    (When there are many un-connected Classes, they can clutter up the diagram making it harder to trace the relationships between the connected Classes.)
* `-only-edgeless`: to hide/exclude all Classes **with** any edges/arrows
    This would be useful for simplifying/filtering the output. E.g. To easily identify un-connected Classes during an API review.
    (E.g. Un-connected Classes often get 'scattered', with seemingly haphazard locations, based on where they 'fit' between connected Classes and their edges/arrows. Hiding edges and/or edged-Classes can reduce or eliminate such haphazard layouts, which is useful in certain situations.)
* `-label-edges`: to include text labels on all rendered edges/arrows
    This would make arrows with different heads/tails easier to distinguish from each other.
    (E.g. When multiple edges all start or end at the same Class, it can be difficult to identify which head/tail type a particular arrow has.)

Note: For all of the hiding/filtering options above, you have 2 implementation options: either exclude 'hidden' graph content from the output completely, OR render the hidden content as you normally would, except as commented-out puml (so the diagram rendering would ignore hidden content, but the hidden content could be selectively un-hidden manually). Or you could give the user the choice between those 2 options by adding an additional `-excluded-as-comments` CLI flag (or similar).

Related: Similar to enhancement #28, but for additional CLI switches.

**Comment by jfeliu007** [comment]
This could definitely be done, although not all in one shot. I will separate this in issues so we can discuss each one individually (if you do not mind). I just implemented a feature into the Parser that will allow me to pass option to the renderer, which I think hits the nail with what you are asking here. I am glad I thought it could be useful. 

We could use the RenderingOptions structure for this. 

Great input @Justin-W . Thank you very much.

I will create a separate issue for each of the suggestions in this one.

**Comment by jfeliu007** [comment]
I created issues for each of the suggestions. The -excluded-as-comment option could really increment the complexity of some of the implementation. I think I will do a combination of commented out portions and using specific directives in plantuml (e.g. show fields) which will easily allow anyone to activate or deactivate the fields.

**Comment by jfeliu007** [comment]
@Justin-W , could you expand with more examples what your suggestion for the labels is? Issue #58 is the specific issue related to this recommendation.

**Comment by Justin-W** [comment]
> I created issues for each of the suggestions. The -excluded-as-comment option could really increment the complexity of some of the implementation. I think I will do a combination of commented out portions and using specific directives in plantuml (e.g. show fields) which will easily allow anyone to activate or deactivate the fields.

I concur. That sounds like a good approach.

> We could use the RenderingOptions structure for this.

I noticed that struct, but saw that it currently was pretty sparse on fields.

> I will create a separate issue for each of the suggestions in this one.

No objections. I figured you would probably want to do so, but figured I'd let you decide whether to deal with them separately or not.

P.S. Cool tool. Keep up the good work. Cheers. :)

**Comment by Justin-W** [comment]
> I created issues for each of the suggestions.

For reference: #53, #54, #55, #56, #57, #58.

**Comment by Justin-W** [comment]
Closing this issue since the status of each separate CLI flag is being tracked via separate issues: #53, #54, #55, #56, #57, #58.
