### ISSUE TITLE
Enhancement: Additional CLI options to control rendered output -no-fields

### ISSUE THREAD

**Issue by jfeliu007** [jfeliu007/goplantuml#53]
Provide the CLI flag
```-no-fields```
To hide/exclude Classes' "fields"
This would be useful for simplifying/filtering the output. E.g. Reducing the size of the Class nodes (by including less intra-Class detail) simplifies the graph layout, and makes it easier to trace inter-Class relationships during an API review of the coupling between Classes.

**Comment by jfeliu007** [comment]
I decided to name this flag ```-hide-fields``` it looks more like an action. The result would be to add the ```hide fields``` directive at the bottom of the diagram so that no fields render, but the fields remain in the diagram. The user can manually set this up easily if desired.

**Comment by Justin-W** [comment]
Works great! Thanks!

Tested #53 and #54 together with `goplantuml -recursive -hide-fields -hide-methods .`
