### ISSUE TITLE
Enhancement: Additional CLI options to control rendered -no-methods

### ISSUE THREAD

**Issue by jfeliu007** [jfeliu007/goplantuml#54]
Provide the CLI flag 
```-no-methods```
to hide/exclude Classes' "methods"
This would be useful for simplifying/filtering the output. E.g. Reducing the size of the Class nodes (by including less intra-Class detail) simplifies the graph layout, and makes it easier to trace inter-Class relationships during an API review of the coupling between Classes.

**Comment by jfeliu007** [comment]
Decided to use the flag -hide-methods. This will be similar to the way we handled #53 in which we will add the ```hide methods``` directive at the end when the options is provided

**Comment by Justin-W** [comment]
Works great! Thanks!

Tested #53 and #54 together with `goplantuml -recursive -hide-fields -hide-methods .`
