### ISSUE TITLE
Enhancement: Additional CLI options to control rendered output -label-edges

### ISSUE THREAD

**Issue by jfeliu007** [jfeliu007/goplantuml#58]
Provide the CLI flag
```-label-edges```
To include text labels on all rendered edges/arrows
This would make arrows with different heads/tails easier to distinguish from each other.
(E.g. When multiple edges all start or end at the same Class, it can be difficult to identify which head/tail type a particular arrow has.)

**Comment by Justin-W** [comment]
> @Justin-W , could you expand with more examples what your suggestion for the labels is?

You use different arrow heads/tails for different types of relations between classes. I was just thinking of describing the arrows based on how you're using them. I am assuming the labels would be something similar to:

* implements
* uses
* extends
* (etc.)

**Comment by jfeliu007** [comment]
Got it.

**Comment by Justin-W** [comment]
Verified `goplantuml -show-connection-labels` works. Thanks!
