### ISSUE TITLE
Invalid edge for simple type

### ISSUE THREAD

**Issue by Justin-W** [jfeliu007/goplantuml#65]
I'm seeing the following invalid puml generated:

```plantuml
[]float64 #.. config.NumSlice
```

I think the go code that is causing the above line is this:

```go
type NumSlice []float64
```

FYI: This error seems very similar to #49, but still exists despite the recent fixes for #49 and #50.

**Comment by jfeliu007** [comment]
You should be getting something like this
```
"__builtin__.[]float64" #.. "gofile.NumSlice"
```
Make sure you are running the lates master. I have not cut any tags yet for a new release, so if you are using one of the releases it will not work.

**Comment by Justin-W** [comment]
Verified using latest (via `go get -u`). I now get the following output:

```plantuml
"__builtin__.[]float64" #.. "config.NumSlice"
```

Thanks!
