### ISSUE TITLE
Generate relation for private fields

### ISSUE THREAD

**Issue by ericbrisrubio** [jfeliu007/goplantuml#97]
Private fields are not being related to their dependencies.

**Comment by n-is** [comment]
@ericbrisrubio Did you find any way to do this?

**Comment by ericbrisrubio** [comment]
@n-is yes, there is a specific param we can switch and this is going to work. The only issue here could be a lot of dependencies being shown at the same time in the resultant image.

**Comment by n-is** [comment]
@ericbrisrubio which param does the work? I would like to observe the proper dependencies from a package level so that it helps for those who would want to understand how the package is configured.

**Comment by jfeliu007** [comment]
We need to make updates to the source. I am going to implement a new argument in the command line and in the rendering options for this.

**Comment by jfeliu007** [comment]
Thanks for pointing this out. I have added this functionality to the library and it is accessible through the CLI as an optional parameter -show-private-aggregations. If you are using the CLI make sure you also add the -show-aggregations flag since aggregations are not rendered by default

**Comment by jfeliu007** [comment]
There is a new tag which includes this feature https://github.com/jfeliu007/goplantuml/tree/v1.5.0

**Comment by n-is** [comment]
That was fast. Thank you. :)

**Comment by jfeliu007** [comment]
@n-is Let me know if this works for you

**Comment by n-is** [comment]
It is working fine. And I am already using it for documenting low-level packages in go projects. Thanks a lot.
